<Project>
  <PropertyGroup>
    <Version>0.0.1</Version>
    <NetVersion>10</NetVersion>
    <KernelDriverServiceName>vgk</KernelDriverServiceName>
    <UserLevelService>vgc</UserLevelService>
    <GameProcesses>RiotClientServices;RiotClientCrashHandler;Riot Client</GameProcesses>
    <Company>H2O Productions</Company>
    <Product>Vanguard Manager</Product>
    <ServiceName>VanguardManager</ServiceName>
  </PropertyGroup>

  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <AnalysisMode>Recommended</AnalysisMode>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Matteo Dell'Acqua</Authors>
    <PackageVersion>$(Version)</PackageVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <RepositoryUrl>https://github.com/MatteoH2O1999/VanguardManager</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © Matteo Dell'Acqua 2026-$([System.DateTime]::Now.ToString("yyyy"))</Copyright>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net$(NetVersion).0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>true</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <UseWindowsForms>true</UseWindowsForms>
    <DebugSymbols Condition="'$(Configuration)' == 'release'">false</DebugSymbols>
    <GenerateRuntimeConfigurationFiles Condition="'$(Configuration)' == 'release'">false</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile Condition="'$(Configuration)' == 'release'">false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="ServiceName" Value="$(ServiceName)" />
    <AssemblyMetadata Include="KernelDriverServiceName" Value="$(KernelDriverServiceName)" />
    <AssemblyMetadata Include="UserLevelService" Value="$(UserLevelService)" />
    <AssemblyMetadata Include="GameProcesses" Value="$(GameProcesses)" />
  </ItemGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectExtension) == '.csproj' And $(SkipDirectoryDeps) != true">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(NetVersion).*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="$(NetVersion).*" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="$(NetVersion).*" />
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <PackageReference Include="Vanara.PInvoke.Security" Version="5.0.5" />
  </ItemGroup>
</Project>
