<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <AnalysisMode>Recommended</AnalysisMode>
    <Version>0.0.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Matteo Dell'Acqua</Authors>
    <PackageVersion>$(Version)</PackageVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <RepositoryUrl>https://github.com/MatteoH2O1999/VanguardManager</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>Copyright © Matteo Dell'Acqua 2026-$([System.DateTime]::Now.ToString("yyyy"))</Copyright>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
