<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>updater</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manager.Vanguard.Launcher\Manager.Vanguard.Launcher.csproj" />
    <ProjectReference Include="..\Manager.Vanguard.Service\Manager.Vanguard.Service.csproj" />
  </ItemGroup>
</Project>
