<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <AssemblyName>service</AssemblyName>
    <AssemblyTitle>Background service for Vanguard Manager</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manager.Vanguard.Common\Manager.Vanguard.Common.csproj" />
  </ItemGroup>
</Project>
